// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNURiaB4d3l7AhM9N4iDK0BAhxvf3tab8',
    appId: '1:174158709990:web:b6ba1b4c1cd83a4506e727',
    messagingSenderId: '174158709990',
    projectId: 'cours-flutter-74dea',
    authDomain: 'cours-flutter-74dea.firebaseapp.com',
    storageBucket: 'cours-flutter-74dea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXJZy2MPkBTXC7fax028ZENSXxLzspXWA',
    appId: '1:174158709990:android:3985f05892fa038306e727',
    messagingSenderId: '174158709990',
    projectId: 'cours-flutter-74dea',
    storageBucket: 'cours-flutter-74dea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbib7EL9qngGN50z-lWMBPV-gaweJzyA',
    appId: '1:174158709990:ios:e3b71b5bc124e64e06e727',
    messagingSenderId: '174158709990',
    projectId: 'cours-flutter-74dea',
    storageBucket: 'cours-flutter-74dea.appspot.com',
    iosBundleId: 'com.example.messagerie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbib7EL9qngGN50z-lWMBPV-gaweJzyA',
    appId: '1:174158709990:ios:eb557b9f72ac871806e727',
    messagingSenderId: '174158709990',
    projectId: 'cours-flutter-74dea',
    storageBucket: 'cours-flutter-74dea.appspot.com',
    iosBundleId: 'com.example.messagerie.RunnerTests',
  );
}
